on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bwb
        uses: addnab/docker-run-action@v3
        with:
          image: biodepot/bwb:latest
          options: --privileged --group-add root --name bwb
          run: |
              echo `docker top bwb | grep orange-canvas`
