on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: biodepot/bwb:latest
      options: --privileged --group-add root --entrypoint /bin/bash
    steps:
      - name: ls
        run: ls
      - name: ls ..
        run: ls ..
