on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bwb
        uses: addnab/docker-run-action@v3
        with:
          image: biodepot/bwb:latest
          options: --privileged --group-add root
          run: |
              # if [ -f ../startup.sh ] ; then echo "Bwb successfully launched." ; else exit 1 ; fi
              if [ -f startup.sh ] ; then echo "Bwb successfully launched." ; else exit 1 ; fi
