on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bwb
        uses: addnab/docker-run-action@v3
        with:
          image: biodepot/bwb:latest
          options: -p 6080:6080 --privileged --group-add root -v /tmp/.X11-unix:/tmp/.X11-unix -v /var/run/docker.sock:/var/run/docker.sock
          run: |
              bash ../startup.sh
              sleep 5
              docker ps
              docker top $(docker ps --filter ancestor=biodepot/bwb --format '{{.Names}}')
              ls -al /root/.fluxbox
              ls /orange3/Orange/canvas/icons/
