on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bwb
        uses: addnab/docker-run-action@v3
        with:
          image: biodepot/bwb:latest
          options: --privileged --group-add root
          - name: Try running startup.sh
            run: bash ../startup.sh
          - name: docker ps
            run: docker top $(docker ps --format "{{.Names}}")
