on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: biodepot/bwb:latest
    steps:
      - name: test steps
        run: docker top $(docker ps --format "{{.Names}}") | grep orange-canvas
